name: windesign
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"  # Ensure compatibility with Dart 3.3.3

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  http: ^1.2.2  # Updated for compatibility
  editable: ^2.0.0
  pluto_grid: ^8.0.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
